"""shop worksheet

Revision ID: 43e6eb0b2619
Revises: 
Create Date: 2023-06-25 18:13:17.344590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e6eb0b2619'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('wokrsheet', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'shops', ['wokrsheet'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='unique')
    op.drop_column('shops', 'wokrsheet')
    # ### end Alembic commands ###
